### ISSUE TITLE
EXC_BAD_ACCESS on missing image.

### ISSUE THREAD

**Issue by Socapex** [axlib/axFrameworks#1]
We shouldn't crash if media isn't present. We should gracefully degrade, with an debug output error message and a color filled rect?

**Comment by alexarse** [comment]
je comprend pas sa arrive de ou tous cela

**Comment by Socapex** [comment]
code 18, jpense que je set pas le opengl handler? Mais tse, c'est tellement facile de naviguer un example qui est un desktop AU COMPLET lol

Comment tu hook le fucking openGL view?

**Comment by alexarse** [comment]
t tu sur linux ou mac la ?

**Comment by Socapex** [comment]
mac, je fait mon app pour la reunion. Jveux juste un foutu bouton qui output a stdout. J'vais etre content avec ca. J'ai un ax::App pis thats it... Comment je passe le OpenGL View a axLib?

**Comment by alexarse** [comment]
t'a copier la xib dans ton projet? pi tajoute opengl et cocoa framewokr ?

**Comment by Socapex** [comment]
J'ai creer un nouveau xib... Faut je copie celui de eos?

**Comment by alexarse** [comment]
copie celui de axFrameowkr/modules/axCore/core/mac

**Comment by Socapex** [comment]
Allright, je l'ai eu jcrois. C'est tout rouge fonce. J'ai overload axAppDelegate pour le OpenGL View et le Delegate. Puis deconnecter la window referencing outlet.

**Comment by alexarse** [comment]
ouin c suposer être rouge mais tu devrait pas bosser direct dans le .xib mais si sa marche c bon

**Comment by Socapex** [comment]
Ben j'gosse pas direct dans le xib. Overloader des classes c'est pas mal normal. Par exemple jai encore le crash quand jessai de loader une image :/

**Comment by alexarse** [comment]
si tu utilise le .xib file du truc et tout devrait marche pas de objectif c

**Comment by alexarse** [comment]
jeter fait un petit code

class CPanel : public ax::Window
{
public:
    CPanel(ax::App* app, const ax::Rect& rect):
    ax::Window(app, rect)
    {
        
        ax::Button::Info btn_info(ax::Color(0.6),
                                  ax::Color(0.7),
                                  ax::Color(0.5),
                                  ax::Color(0.6),
                                  ax::Color(0.0),
                                  ax::Color(0.0));
        
        ax::Button* btn1 = new ax::Button(this, ax::Rect(100, 100, 50, 50),
                                          ax::Button::Events([](ax::Event::Msg* msg) { ax::Print("Fuck");}),
                                          btn_info, "", "Test1");
        
        ax::Button* btn2 = new ax::Button(this, ax::Rect(160, 100, 50, 50),
                                         GetOnMyButtonClick(),
                                         btn_info, "", "Test2");
    }
    
private:
    axEVENT_ACCESSOR(ax::Button::Msg, OnMyButtonClick);
    void OnMyButtonClick(const ax::Button::Msg& msg)
    {
        ax::Print("Double fuck");
    }
    
    virtual void OnPaint()
    {
        ax::GC gc;
        ax::Rect rect(GetDrawingRect());
        
        gc.SetColor(ax::Color(1.0));
        gc.DrawRectangle(rect);
    }
};

int main()
{
    ax::App app;
    
    app.AddMainEntry([&app]()
    {
        app.SetFrameSize(ax::Size(500, 500));
        CPanel* panel = new CPanel(&app, ax::Rect(0, 0, 500, 500));
    });
    
    app.MainLoop();
    
    return 0;
}

**Comment by Socapex** [comment]
Ouin... tu as le temps se soir pour une reunion skype? Ta librairie c'est pratiquement wxWidget... J'trippe pas full la. Peux-tu gosser Anis stp?

**Comment by alexarse** [comment]
jpart de lecole la on skype vers 1h30 ?? C’est sur que ca ressemble a wxWidget. 



class CPanel : public ax::Window
{
public:
    CPanel(ax::App* app, const ax::Rect& rect):
    ax::Window(app, rect)
    {
        
        ax::Button::Info btn_info(ax::Color(0.6),
                                  ax::Color(0.7),
                                  ax::Color(0.5),
                                  ax::Color(0.6),
                                  ax::Color(0.0),
                                  ax::Color(0.0));
        
        ax::Button* btn1 = new ax::Button(this, ax::Rect(100, 100, 50, 50),
                                          ax::Button::Events([](ax::Event::Msg* msg) { ax::Print("Fuck");}),
                                          btn_info, "", "Test1");
        
        ax::Button* btn2 = new ax::Button(this, ax::Rect(160, 100, 50, 50),
                                         GetOnMyButtonClick(),
                                         btn_info, "", "Test2");
        
        
        ax::Button::Info btn2_info(ax::Color(0.6, 0.0),
                                   ax::Color(0.7, 0.0),
                                   ax::Color(0.5, 0.0),
                                   ax::Color(0.6, 0.0),
                                   ax::Color(0.0, 0.0),
                                   ax::Color(0.0, 0.0));
        
        ax::Button* btn3 = new ax::Button(this, ax::Rect(220, 100, 60, 25),
                                          GetOnMyButtonClickArg(),
                                          btn2_info, "axButtonImg.png", "Test3", 0, "MonMsg fuck");
    }
    
private:
    axEVENT_ACCESSOR(ax::Button::Msg, OnMyButtonClick);
    void OnMyButtonClick(const ax::Button::Msg& msg)
    {
        ax::Print("Double fuck");
    }
    
    axEVENT_ACCESSOR(ax::Button::Msg, OnMyButtonClickArg);
    void OnMyButtonClickArg(const ax::Button::Msg& msg)
    {
        ax::Print(msg.GetMsg());
    }
    
    virtual void OnPaint()
    {
        ax::GC gc;
        ax::Rect rect(GetDrawingRect());
        
        gc.SetColor(ax::Color(1.0));
        gc.DrawRectangle(rect);
    }
};

int main()
{
    ax::App app;
    
    app.AddMainEntry([&app]()
    {
        app.SetFrameSize(ax::Size(500, 500));
        CPanel* panel = new CPanel(&app, ax::Rect(0, 0, 500, 500));
    });
    
    app.MainLoop();
    
    return 0;
}

**Comment by Socapex** [comment]
J;suis sur skype. Call moi quand t'arrive, on jase ;) Je email Aniss aussi.
